### ISSUE TITLE
Confusing inactive download buttons

### ISSUE THREAD

**Issue by xaur** [decred/dexweb#31]
I checked https://dex.decred.org/ and my first instinct was to hit the sexy Download buttons expecting I would get the new standalone version.

They are kind of disabled but still "blue enough" and are tempting to click (there is no "bluer" button in view to have a contrast to see that they are disabled). Then I noticed the "NOTE" above, realized they are disabled and not clickable by design, and figured I need to click that link.

I know this is a silly "bug" but maybe user navigation can be made smoother here. A few ideas:

- Add word "Decrediton" to each of the 3 Decrediton download tiles to communicate what exactly will be downloaded
  - OR group Decrediton downloads under a visible **Decrediton with DEX client** header or something
- Make 3 tiles for Decrediton downloads totally gray to give no false hope of being clickable
- Add 4th download tile for the standalone version (with a note that OS and architecture will be picked in the next step).
  - This allows to also remove the less visible "Click here to download the standalone DCRDEX application instead  ↓" link below. It is less visible because it's a line of text and not a big download tile.
  - Each download option having a tile may look more consistent and intuitive.

![dex-dl-buttons](https://user-images.githubusercontent.com/24484727/195157448-7adeda85-9d39-460e-97aa-64a5a4eebefa.png)

**Comment by chappjc** [comment]
This is temporary because the old Decrediton downloads were causing major problem.  They will be replaced and reactivated asap.  https://github.com/decred/dexweb/pull/30

I hope this does not become a recurring issue where we have to disable them often, but I like all of your bullet point suggestions.  I would support those changes.
